version: "3.9"

services:
  web:
    image: nginx:alpine
    container_name: eventcube_web
    depends_on:
      - app
    ports:
      - "8000:80"
    volumes:
      - ./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  app:
    build: .
    container_name: eventcube_app
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - .:/var/www/html
